CREATE TABLE IF NOT EXISTS tiers (
    id SERIAL PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    rank INTEGER NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    username TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    tier_id INTEGER NOT NULL REFERENCES tiers(id) ON DELETE RESTRICT,
    is_admin BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS sessions (
    token UUID PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    expires_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS question_pools (
    id SERIAL PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    tier_id INTEGER NOT NULL REFERENCES tiers(id) ON DELETE RESTRICT,
    csv_text TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

INSERT INTO tiers (name, rank)
VALUES ('public', 0)
ON CONFLICT (name) DO NOTHING;
